[package]
name = "http_server_external_requests"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
reqwest = { version = "0.12.22", features = ["json"] }
tokio = { version = "1.47.1", features = ["full"] }
